### ISSUE TITLE
Idea: optionally support Timex in last_modified and related callbacks (depending on the return type?)

### ISSUE THREAD

**Issue by yrashk** [kbrw/ewebmachine#12]
Timex is a great datetime library: https://hex.pm/packages/timex

**Comment by awetzel** [comment]
Yes pretty good idea, add a dependency is against the initial goal of this webmachine rewriting, but actually make it optional seems doable and useful. I will do it when I find time next week.

**Comment by tomekowal** [comment]
There is also calendar library: https://github.com/lau/calendar It might be a good idea to wait until Elixir 1.3 which will provide date and time types http://tuvistavie.com/2016/elixir-1-3/#calendar-datatypes Then the libraries will have to adjust to those types :)

**Comment by Shakadak** [comment]
Hi, is this still of interest ? I'd like to understand the need and the context.

**Comment by tomekowal** [comment]
I commented in 2016 but I am not interested anymore. Thanks for asking!

**Comment by Shakadak** [comment]
Alright, the need didn't come up in our projects either, so I'm closing this.
